KitchenSink/Models/Dogs/All.cs
using System.Collections.Generic;

namespace KitchenSink.Models.Dogs
{
    public class All
    {
        public IEnumerable<DogItem> DogsItems { get; set; }
    }
}

KitchenSink/Models/Dogs/DogItem.cs
namespace KitchenSink.Models.Dogs
{
    public class DogItem
    {
        public string Id { get; set; }
        public string Type { get; set; }
        public string ThumbnailImageUrl { get; set; }
        public string LargeImageUrl { get; set; }
    }
}

KitchenSink/Models/Dogs/SingleDogItem.cs
using System;
using System.Collections.Generic;

namespace KitchenSink.Models.Dogs
{
    public class SingleDogItem
    {
        public string Id { get; set; }
        public string Type { get; set; }
        public decimal AverageCost { get; set; }
        public int NumberAvailable { get; set; }
        public bool IsMale { get; set; }
        public DateTime? Birthday { get; set; }
        public IEnumerable<SingleDogItemPicture> Pictures { get; set; }
    }
}

KitchenSink/Models/Dogs/SingleDogItemPicture.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace KitchenSink.Models.Dogs
{
    public class SingleDogItemPicture
    {
        public string ThumbnailImageUrl { get; set; }
        public string LargeImageUrl { get; set; }
    }
}

KitchenSink/Controllers/DogsController.cs
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using System.Web.Mvc;
using Contentful.NET;
using Contentful.NET.DataModels;
using Contentful.NET.Search;
using Contentful.NET.Search.Filters;
using KitchenSink.Models.Dogs;

namespace KitchenSink.Controllers
{
    public class DogsController : AsyncController
    {
        // Injected by Unity App_Start/UnityConfig.cs
        private readonly IContentfulClient _contentfulClient;

        public DogsController(IContentfulClient contentfulClient)
        {
            _contentfulClient = contentfulClient;
        }

        // GET: All Dogs
        public async Task<ActionResult> AllAsync(CancellationToken cancellationToken)
        {
            
            var results = await _contentfulClient.SearchAsync<Entry>(cancellationToken, new[]
            {
                // Only search for the 'Dog' content type
                new EqualitySearchFilter(BuiltInProperties.ContentType, "3KzwWGrzry422cEkMCA2o6"),
            }, 
            includeLevels: 1 // Ensure we retrieve the linked assets inside this one request - we want to get the Images for the dogs too
            );
            
            return View(GetAllDogsFromContentfulResult(results));
        }

        [HttpPost]
        public async Task<ActionResult> SearchAsync(string criteria, CancellationToken cancellationToken)
        {
            var results = await _contentfulClient.SearchAsync<Entry>(cancellationToken, new ISearchFilter[]
            {
                // Only search for the 'Dog' content type
                new EqualitySearchFilter(BuiltInProperties.ContentType, "3KzwWGrzry422cEkMCA2o6"),
                new FullTextSearchFilter(criteria)
            },
            includeLevels: 1 // Ensure we retrieve the linked assets inside this one request - we want to get the Images for the dogs too
            );
            ViewBag.FromSearch = true;
            ViewBag.Criteria = criteria;
            return View("All", GetAllDogsFromContentfulResult(results));
        }

        private static All GetAllDogsFromContentfulResult(SearchResult<Entry> results)
        {
            return new All
            {
                DogsItems = results.Items
                    // Retrieve the ImageId from the linked 'mainPicture' asset
                    // NOTE: We could merge all of these Select() statements into one, but this way we only have to call dog.GetLink() and dog.GetString()
                    //       once, which improves performance.
                    .Select(dog => new
                    {
                        dog.SystemProperties.Id,
                        ImageId = dog.GetLink("mainPicture").SystemProperties.Id,
                        Type = dog.GetString("dogType")
                    })
                    // Now find the included 'Asset' details from the corresponding ImageId
                    .Select(dog => new
                    {
                        dog.Id,
                        ImageUrl =
                            results.Includes.Assets.First(asset => asset.SystemProperties.Id == dog.ImageId)
                                .Details.File.Url,
                        dog.Type
                    })
                    // Now we map our calculated data to our model
                    .Select(dog => new DogItem
                    {
                        Id = dog.Id,
                        LargeImageUrl =
                            ImageHelper.GetResizedImageUrl(dog.ImageUrl, 500, 500, ImageHelper.ImageType.Jpg, 75),
                        ThumbnailImageUrl =
                            ImageHelper.GetResizedImageUrl(dog.ImageUrl, 150, 150, ImageHelper.ImageType.Png),
                        Type = dog.Type
                    })
            };
        }

        public async Task<ActionResult> DetailAsync(string id, CancellationToken cancellationToken)
        {
            var searchResults = await _contentfulClient.SearchAsync<Entry>(cancellationToken, new []
            {
                // Only search for the ID of this dog
                new EqualitySearchFilter(BuiltInProperties.SysId, id), 
            }, includeLevels:1); // We COULD do a Get instead of a Search here, but only a Search includes linked assets
            if (searchResults.Total == 0) return HttpNotFound();
            var result = searchResults.Items.First();
            // Retrieve any linked pictures
            var allPictures = result.GetType<IEnumerable<Link>>("otherPictures");
            var model = new SingleDogItem
            {
                // Retrieve the necessary data from the Entry
                Type = result.GetString("dogType"),
                AverageCost = result.GetType<decimal>("averageCost"),
                Birthday = result.GetDateTime("birthDate"),
                Id = result.SystemProperties.Id,
                IsMale = result.GetBoolean("isMale") == true,
                NumberAvailable = result.GetType<int>("numberAvailable"),
                // Get a thumbnail AND a large image for each picture
                Pictures = allPictures == null ? null : allPictures
                    .Select(pic => new {pic.SystemProperties.Id})
                    .Select(
                        pic =>
                            new
                            {
                                ImageUrl =
                                    searchResults.Includes.Assets.First(asset => asset.SystemProperties.Id == pic.Id)
                                        .Details.File.Url
                            })
                    .Select(pic => new SingleDogItemPicture
                    {
                        LargeImageUrl =
                            ImageHelper.GetResizedImageUrl(pic.ImageUrl, 500, 500, ImageHelper.ImageType.Jpg, 75),
                        ThumbnailImageUrl =
                            ImageHelper.GetResizedImageUrl(pic.ImageUrl, 150, 150)
                    })
                /* If we don't care about resizing images, it becomes a bit easier:
                 * 
                 * Pictures = allPictures.Select(pic => new
                 * {
                 *     ImageUrl = searchResults.Includes.Assets.First(asset => asset.SystemProperties.Id == pic.SystemProperties.Id).Details.File.Url
                 * })
                 * 
                 */ 
            };
            
            return View(model);
        }
    }
}

KitchenSink/Views/Dogs/All.cshtml
@model KitchenSink.Models.Dogs.All

@{
    ViewBag.Title = "All Dogs";
}

<div class="all">
    @if (ViewBag.FromSearch as bool? == true)
    {
        <h2>Search Results</h2>
        <p>
            For: <strong>@ViewBag.Criteria</strong>
        </p>
    }
    else
    {
        <h2>All Dogs</h2>
    }
    

    <ul>
        @foreach (var dog in Model.DogsItems)
        {
            <li>
                <a href="@dog.LargeImageUrl" class="image">
                    <img src="@dog.ThumbnailImageUrl" alt="Photo of a @dog.Type">
                </a>
                <div class="description">
                    @dog.Type<br/>
                    <a class="details" href="@Url.Action("Detail", new {id = dog.Id})">
                        View Details
                    </a>
                </div>

            </li>
        }
    </ul>
</div>

KitchenSink/Views/Dogs/Detail.cshtml
@model KitchenSink.Models.Dogs.SingleDogItem

@{
    ViewBag.Title = "title";
}

<div class="detail">
    <h2>@Model.Type</h2>

    <ul>
        <li>
            <strong>Average Cost:</strong>
            @string.Format("{0:C0}", Model.AverageCost)
        </li>
        <li>
            <strong>Number Available:</strong>
            @Model.NumberAvailable
        </li>
        <li>
            <strong>Gender:</strong>
            @(Model.IsMale ? "Male" : "Female")
        </li>
        @if (Model.Birthday.HasValue)
        {
            <li>
                <strong>Birthday:</strong>
                @Model.Birthday.Value.ToLongDateString()
            </li>
        }
        @if (Model.Pictures != null)
        {
            <li>
                <strong>Pictures:</strong>
                @foreach (var picture in Model.Pictures)
                {
                    <a href="@picture.LargeImageUrl" target="_blank">
                        <img src="@picture.ThumbnailImageUrl" alt=""/>
                    </a>
                }
            </li>
        }
    </ul>
</div>

KitchenSink/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width"/>
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,600' rel='stylesheet' type='text/css'>
    <link href="~/Content/master.css" rel="stylesheet"/>
    <title>Kitchen Sink</title>
</head>
<body>
<div class="body-wrapper">
    <header>
        <h1>Directory</h1>
    </header>
    <div class="search">
        @using (Html.BeginForm("Search", "Dogs"))
        {
            <input placeholder="Search" id="criteria" name="criteria" />
        }
    </div>
    <div class="main-content">
        @RenderBody()
    </div>
    <footer>
        
    </footer>
</div>
</body>
</html>